name: Render documentation

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  UV_VERSION: 0.3.2  # Pin the version of UV

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
    - name: Render the documentation
      run: >
        uv run
        sphinx-build
        -M html ./doc ./build/sphinx
        -vv
        --jobs=auto
        --show-traceback
        --fail-on-warning
