name: Lint source code

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  UV_VERSION: 0.3.2  # Pin the version of UV

jobs:
  # If you update any of these commands, don't forget to update the equivalent
  # tox environment
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
    - name: Lint with Ruff
      run: uv run ruff check . --output-format github
    - name: Format with Ruff
      run: uv run ruff format . --diff

  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
    - name: Lint with flake8
      run: uv run flake8 .

  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
    - name: Type check with mypy
      run: uv run mypy

  # docs-lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Install uv
  #     run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
  #   - name: Install dependencies
  #     run: uv pip install --upgrade sphinx-lint
  #   - name: Lint documentation with sphinx-lint
  #     run: make doclinter

  # twine:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: "3"
  #   - name: Install uv
  #     run: >
  #       curl --no-progress-meter --location --fail
  #       --proto '=https' --tlsv1.2
  #       "https://astral.sh/uv/install.sh"
  #       | sh
  #   - name: Install dependencies
  #     run: uv pip install --upgrade twine build
  #   - name: Lint with twine
  #     run: |
  #       python -m build .
  #       twine check dist/*
